### ISSUE TITLE
HTTP error! status: 500

### ISSUE THREAD

**Issue by shuntera** [brett-baudin-consulting/uMdali#14]
Under WSL2 on a Windows 11 machine I have Docker serving up Ollama and on my host machine when I go to http://localhost:11434 I get the Ollama page coming up with 'Ollama is running'.

uMdali runs on the same Docker under Windows 11/WSL2. The web interface comes up on localhost:8080 OK, and I go in and choose ollama/mistral as the model (I have tested that the model is downloaded).

I entered a query "When was the Battle of Trafalgar" and hit Enter.  Immediately a line comes up that says "HTTP error! status: 500"

Screenshot attached

![uMdali](https://github.com/brett-baudin-consulting/uMdali/assets/11050796/275e14fc-6350-4480-a3a7-0467b3789e2c)

**Comment by brett-baudin-consulting** [comment]
Replace localhost with your actual ip.

**Comment by shuntera** [comment]
In what, the IP address for Ollama or the IP address for uMdali?
